version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: okami-postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okami-api
    env_file: .env
    labels:
      - "traefik.http.routers.okamiapi.rule=Host(`okami-api.phmarques.com.br`)"
      - "traefik.http.routers.okamiapi.entrypoints=web,websecure"
      - "traefik.http.routers.okamiapi.tls.certresolver=myresolver"
    networks:
      - web
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./prisma:/app/prisma
      - ./uploads:/app/uploads
    command: sh -c "sleep 10 && bun run db:seed:users && bun --hot src/index.ts"
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: okami-adminer
    ports:
      - "8081:8080"
    networks:
      - web
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  web:
    external: true